In [9]:
# Import required libraries
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import sklearn
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor

# Import necessary modules
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn.metrics import r2_score

In [10]:
df = pd.read_csv('/content/diabetes.csv') 
print(df.shape)
df.describe().transpose()

(768, 9)


count        mean         std     min       25%  \
Pregnancies               768.0    3.845052    3.369578   0.000   1.00000   
Glucose                   768.0  120.894531   31.972618   0.000  99.00000   
BloodPressure             768.0   69.105469   19.355807   0.000  62.00000   
SkinThickness             768.0   20.536458   15.952218   0.000   0.00000   
Insulin                   768.0   79.799479  115.244002   0.000   0.00000   
BMI                       768.0   31.992578    7.884160   0.000  27.30000   
DiabetesPedigreeFunction  768.0    0.471876    0.331329   0.078   0.24375   
Age                       768.0   33.240885   11.760232  21.000  24.00000   
Outcome                   768.0    0.348958    0.476951   0.000   0.00000   

                               50%        75%     max  
Pregnancies                 3.0000    6.00000   17.00  
Glucose                   117.0000  140.25000  199.00  
BloodPressure              72.0000   80.00000  122.00  
SkinThickness              23.0000   32.00000   99.00  
Insulin                    30.5000  127.25000  846.00  
BMI                        32.0000   36.60000   67.10  
DiabetesPedigreeFunction    0.3725    0.62625    2.42  
Age                        29.0000   41.00000   81.00  
Outcome                     0.0000    1.00000    1.00

In [11]:
target_column = ['Outcome'] 
predictors = list(set(list(df.columns))-set(target_column))
df[predictors] = df[predictors]/df[predictors].max()
df.describe().transpose()

count      mean       std       min       25%  \
Pregnancies               768.0  0.226180  0.198210  0.000000  0.058824   
Glucose                   768.0  0.607510  0.160666  0.000000  0.497487   
BloodPressure             768.0  0.566438  0.158654  0.000000  0.508197   
SkinThickness             768.0  0.207439  0.161134  0.000000  0.000000   
Insulin                   768.0  0.094326  0.136222  0.000000  0.000000   
BMI                       768.0  0.476790  0.117499  0.000000  0.406855   
DiabetesPedigreeFunction  768.0  0.194990  0.136913  0.032231  0.100723   
Age                       768.0  0.410381  0.145188  0.259259  0.296296   
Outcome                   768.0  0.348958  0.476951  0.000000  0.000000   

                               50%       75%  max  
Pregnancies               0.176471  0.352941  1.0  
Glucose                   0.587940  0.704774  1.0  
BloodPressure             0.590164  0.655738  1.0  
SkinThickness             0.232323  0.323232  1.0  
Insulin                   0.036052  0.150414  1.0  
BMI                       0.476900  0.545455  1.0  
DiabetesPedigreeFunction  0.153926  0.258781  1.0  
Age                       0.358025  0.506173  1.0  
Outcome                   0.000000  1.000000  1.0

In [12]:
X = df[predictors].values
y = df[target_column].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=40)
print(X_train.shape); 
print(X_test.shape)

(537, 8)
(231, 8)


In [13]:
from sklearn.neural_network import MLPClassifier

mlp = MLPClassifier(hidden_layer_sizes=(8,8,8), activation='relu', solver='adam', max_iter=500)
mlp.fit(X_train,y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

/usr/local/lib/python3.9/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:1098: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [14]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_train,predict_train))
print(classification_report(y_train,predict_train))

[[320  38]
 [ 72 107]]
              precision    recall  f1-score   support

           0       0.82      0.89      0.85       358
           1       0.74      0.60      0.66       179

    accuracy                           0.80       537
   macro avg       0.78      0.75      0.76       537
weighted avg       0.79      0.80      0.79       537



In [15]:
print(confusion_matrix(y_test,predict_test))
print(classification_report(y_test,predict_test))

[[123  19]
 [ 41  48]]
              precision    recall  f1-score   support

           0       0.75      0.87      0.80       142
           1       0.72      0.54      0.62        89

    accuracy                           0.74       231
   macro avg       0.73      0.70      0.71       231
weighted avg       0.74      0.74      0.73       231



In [16]:
# Import required libraries
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import sklearn
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor

# Import necessary modules
from sklearn.model_selection import train_test_split
#from sklearn.metrics import mean_squared_error
from math import sqrt
#from sklearn.metrics import r2_score

In [17]:
#Import the Data
df = pd.read_csv('/content/wine.csv') 
print(df.shape)
df.describe().transpose()

(178, 14)


count        mean         std     min       25%  \
Wine                  178.0    1.938202    0.775035    1.00    1.0000   
Alcohol               178.0   13.000618    0.811827   11.03   12.3625   
Malic.acid            178.0    2.336348    1.117146    0.74    1.6025   
Ash                   178.0    2.366517    0.274344    1.36    2.2100   
Acl                   178.0   19.494944    3.339564   10.60   17.2000   
Mg                    178.0   99.741573   14.282484   70.00   88.0000   
Phenols               178.0    2.295112    0.625851    0.98    1.7425   
Flavanoids            178.0    2.029270    0.998859    0.34    1.2050   
Nonflavanoid.phenols  178.0    0.361854    0.124453    0.13    0.2700   
Proanth               178.0    1.590899    0.572359    0.41    1.2500   
Color.int             178.0    5.058090    2.318286    1.28    3.2200   
Hue                   178.0    0.957449    0.228572    0.48    0.7825   
OD                    178.0    2.611685    0.709990    1.27    1.9375   
Proline               178.0  746.893258  314.907474  278.00  500.5000   

                          50%       75%      max  
Wine                    2.000    3.0000     3.00  
Alcohol                13.050   13.6775    14.83  
Malic.acid              1.865    3.0825     5.80  
Ash                     2.360    2.5575     3.23  
Acl                    19.500   21.5000    30.00  
Mg                     98.000  107.0000   162.00  
Phenols                 2.355    2.8000     3.88  
Flavanoids              2.135    2.8750     5.08  
Nonflavanoid.phenols    0.340    0.4375     0.66  
Proanth                 1.555    1.9500     3.58  
Color.int               4.690    6.2000    13.00  
Hue                     0.965    1.1200     1.71  
OD                      2.780    3.1700     4.00  
Proline               673.500  985.0000  1680.00

In [18]:
#Let’s set up and split our Data and our Labels
X = df.drop('Wine',axis=1)
y = df['Wine']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [19]:
#Scale the Train and Test Data
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

# Fit only to the training data
scaler.fit(X_train)
StandardScaler(copy=True, with_mean=True, with_std=True)

# Now apply the transformations to the data:
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [20]:
%%time

from sklearn.model_selection import GridSearchCV

params = {'activation': ['relu', 'tanh', 'logistic', 'identity'],
          'hidden_layer_sizes': [(13,), (50,100,), (50,75,100,)],
          'solver': ['adam', 'sgd', 'lbfgs'],
          'learning_rate' : ['constant', 'adaptive', 'invscaling'],
          'max_iter': [500]
         }

mlp_classif_grid = GridSearchCV(MLPClassifier(random_state=123), param_grid=params, n_jobs=-1, cv=5, verbose=5)
mlp_classif_grid.fit(X_train,y_train)

print('Train Accuracy : %.3f'%mlp_classif_grid.best_estimator_.score(X_train, y_train))
print('Test Accuracy : %.3f'%mlp_classif_grid.best_estimator_.score(X_test, y_test))
print('Best Accuracy Through Grid Search : %.3f'%mlp_classif_grid.best_score_)
print('Best Parameters : ',mlp_classif_grid.best_params_)

Fitting 5 folds for each of 108 candidates, totalling 540 fits
Train Accuracy : 1.000
Test Accuracy : 0.956
Best Accuracy Through Grid Search : 0.993
Best Parameters :  {'activation': 'relu', 'hidden_layer_sizes': (13,), 'learning_rate': 'constant', 'max_iter': 500, 'solver': 'sgd'}
CPU times: user 2.66 s, sys: 283 ms, total: 2.95 s
Wall time: 2min 5s


/usr/local/lib/python3.9/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(


In [21]:
mlp = MLPClassifier(activation= 'relu', hidden_layer_sizes= (13,), learning_rate='constant', solver='lbfgs', max_iter=500)
mlp.fit(X_train,y_train)

MLPClassifier(hidden_layer_sizes=(13,), max_iter=500, solver='lbfgs')

In [22]:
predictions = mlp.predict(X_test)

In [23]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,predictions))

[[12  0  0]
 [ 0 18  0]
 [ 0  1 14]]


In [24]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00        12
           2       0.95      1.00      0.97        18
           3       1.00      0.93      0.97        15

    accuracy                           0.98        45
   macro avg       0.98      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45

